### ISSUE TITLE
plot result

### ISSUE THREAD

**Issue by simleopold** [antpiron/RedRibbon#3]
Hi,

I wanted to do a control test by choosing the same list for "a" and "b" (they are differentialy methylated probes ranked by fold change (log)). I expected to have a diagonal with high log p.val and low everywhere else. Here's the result.
![rrhocontrole-np](https://github.com/antpiron/RedRibbon/assets/152170950/40f9253e-cb17-49a6-9f6d-955c37617feb)

I am not a specialist of this type of analysis so I don't understand why I have this kind of plot, maybe you have more explications.

Thank you !

**Comment by antpiron** [comment]
Hi,

>I expected to have a diagonal with high log p.val and low everywhere else.

In fact, this is the diagonal...

Methylation sites are probably more than 1 millions and if you do the perfect overlap (same lists for both), the hypergeometric P-value underflows to zero even with the "long double" real number. As a consequence, the P-value is zero for a large patch (red). [This is a limitation of the way that numbers are represented in computer.](https://en.wikipedia.org/wiki/Extended_precision#x86_extended_precision_format). If you use two distinct list, you most probably won't have this artefact.

Anthony.
